Epoch 1/500










471/471 [==============================] - 22s 46ms/step - loss: 6.9985 - r_squared: 0.0669 - val_loss: 7.0453 - val_r_squared: 0.0960
Epoch 2/500









471/471 [==============================] - 20s 42ms/step - loss: 6.6541 - r_squared: 0.1583 - val_loss: 6.6303 - val_r_squared: 0.2007
Epoch 3/500









471/471 [==============================] - 20s 44ms/step - loss: 6.3841 - r_squared: 0.2261 - val_loss: 6.3900 - val_r_squared: 0.2587
Epoch 4/500









471/471 [==============================] - 20s 43ms/step - loss: 6.1698 - r_squared: 0.2770 - val_loss: 6.1141 - val_r_squared: 0.3226
Epoch 5/500









471/471 [==============================] - 21s 45ms/step - loss: 5.8245 - r_squared: 0.3565 - val_loss: 5.9413 - val_r_squared: 0.3596
Epoch 6/500










471/471 [==============================] - 20s 43ms/step - loss: 5.7503 - r_squared: 0.3727 - val_loss: 5.8849 - val_r_squared: 0.3719
Epoch 7/500









471/471 [==============================] - 21s 44ms/step - loss: 5.6723 - r_squared: 0.3894 - val_loss: 5.8446 - val_r_squared: 0.3809
Epoch 8/500








471/471 [==============================] - 19s 40ms/step - loss: 5.6287 - r_squared: 0.3978 - val_loss: 5.8345 - val_r_squared: 0.3831
Epoch 9/500









471/471 [==============================] - 19s 41ms/step - loss: 5.6058 - r_squared: 0.4032 - val_loss: 5.8353 - val_r_squared: 0.3828
Epoch 10/500









471/471 [==============================] - 20s 44ms/step - loss: 5.5855 - r_squared: 0.4062 - val_loss: 5.8333 - val_r_squared: 0.3837
Epoch 11/500











471/471 [==============================] - 24s 50ms/step - loss: 5.5678 - r_squared: 0.4106 - val_loss: 5.8306 - val_r_squared: 0.3838
Epoch 12/500










471/471 [==============================] - 22s 47ms/step - loss: 5.5386 - r_squared: 0.4163 - val_loss: 5.8255 - val_r_squared: 0.3849
Epoch 13/500
 19/471 [>.............................] - ETA: 19s - loss: 5.6064 - r_squared: 0.4004
Traceback (most recent call last):
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/portion_model.py", line 223, in <module>
    main()
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/portion_model.py", line 217, in main
    iteratively_train_models(data, meal_type)
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/portion_model.py", line 208, in iteratively_train_models
    result = train_portion_model(reduced_data, nn.model_save_path, meal_type, wb_group_name)
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/portion_model.py", line 164, in train_portion_model
    avg_metrics, agg_metrics, best_model = cross_validate_model(X_train, y_train, logpath, meal_type, wb_group_name)
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/portion_model.py", line 125, in cross_validate_model
    nn.train(X_fold_train, y_fold_train, X_fold_val, y_fold_val)
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/portion_model.py", line 55, in train
    self.model.fit(
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/keras/src/engine/training.py", line 1742, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 825, in __call__
    result = self._call(*args, **kwds)
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 857, in _call
    return self._no_variable_creation_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 148, in __call__
    return concrete_function._call_flat(
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py", line 1349, in _call_flat
    return self._build_call_outputs(self._inference_function(*args))
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 196, in __call__
    outputs = self._bound_context.call_function(
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 1457, in call_function
    outputs = execute.execute(
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,

 23/471 [>.............................] - ETA: 18s - loss: 5.5356 - r_squared: 0.4074